version: '3.9'
services:
  db:
    image: postgres:alpine
    volumes:
      - D:\GitRepos\Grocery-Helper\pg_data:/data
    environment:
      POSTGRES_USER: 'svc_grocery_db'
      POSTGRES_PASSWORD: 'groceryService2022!@#'
      POSTGRES_DB: 'grocery_helper'
    ports:
      - "5432:5432"
  # backend:
  #   image: python:slim
  #   volumes:
  #     - D:\GitRepos\Grocery-Helper\backend:/var/lib/postgresql/data/
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
  # rabbitmq:
  #   image: rabbitmq:alpine
  #   depends_on:
  #     - backend
  # worker:
  #   image: python:slim
  #   volumes:
  #     - D:\GitRepos\Grocery-Helper\workers:/data/
  #   depends_on:
  #     - backend
  frontend:
    build: .
    volumes:
      - D:\GitRepos\Grocery-Helper\frontend:/data/
    depends_on:
      - backend
    command: /bin/bash -c "sleep 1500"
    ports:
      - "4200:80"