version: '3.9'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./pg_data:/data
    environment:
      POSTGRES_USER: 'svc_grocery_db'
      POSTGRES_PASSWORD: 'groceryService2022!@#'
      POSTGRES_DB: 'grocery_helper'
    ports:
      - "5432:5432"
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend:/data
  #   depends_on:
  #     - db
  #   ports:
  #     - "8000:8000"
  #   # command: /bin/bash -c "sleep 150000"
  #   command: "python3 manage.py runserver"
  # frontend:
  #   image: grocery_frontend:test
  #   volumes:
  #     - ./frontend:/data
  #   depends_on:
  #     - backend
  #   # command: "cd /data/GroceryHelper && ng serve"
  #   command: /bin/bash -c "sleep 150000"
  #   ports:
  #     - "4200:4200"
  
  # rabbitmq:
  #   image: rabbitmq: