version: '3.9'
services:
  db:
    image: postgres:15-alpine
    init: true
    container_name: grocery-db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file: ./api/.env
    ports:
      - "5432:5432"
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  api:
    # image: grocery-api:test
    image: grocery-api:prod
    init: true
    container_name: grocery-api
    # restart: on-failure:5
    restart: always
    env_file: ./api/.env
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    # command: sleep 15000
  frontend:
    image: grocery-frontend:live
    init: true
    container_name: grocery-frontend
    restart: always
    volumes:
      - ./frontend:/opt/groceryhelper
    command: bash -c "live-server groceryhelper --port=3000" #npm run start #todo add every 10 second refresh of tailwind
    ports:
      - "3000:3000"