version: '3.9'
services:
  db:
    image: postgres:15-alpine
    init: true
    container_name: grocery-db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file: ./api/.env
    ports:
      - "5432:5432"
  api:
    image: grocery-api:test
    init: true
    container_name: grocery-api
    restart: on-failure:5
    env_file: ./api/.env
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: sleep 15000 #go run main.go
  # frontend:
  #   image: grocery-frontend:test
  #   init: true
  #   container_name: grocery-frontend
  #   volumes:
  #     - ./frontend:/opt
  #   depends_on:
  #     - backend
  #   command: bash -c "sleep 15000"
  #   # command: bash -c "ng serve --host 0.0.0.0"
  #   ports:
  #     - "4200:4200"