# Generated by Django 4.0.6 on 2022-07-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of ingredient', max_length=100)),
                ('location', models.CharField(help_text='krogers/sams/etc', max_length=100)),
                ('ailse', models.DecimalField(decimal_places=2, help_text='where it is in the store approximately', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calore_per_serving', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serving_amount', models.DecimalField(decimal_places=2, help_text='how many ounces/pounds?', max_digits=10)),
                ('obtained', models.BooleanField(help_text='is it in the cart?')),
                ('price', models.DecimalField(decimal_places=2, help_text='how much in USD?', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of ingredient', max_length=100)),
                ('location', models.CharField(help_text='krogers/sams/etc', max_length=100)),
                ('ailse', models.DecimalField(decimal_places=2, help_text='where it is in the store approximately', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='how much in USD?', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='how much in USD?', max_digits=10)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grocery_helper_api.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='how much in USD?', max_digits=10)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grocery_helper_api.ingredients')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grocery_helper_api.items')),
            ],
        ),
    ]
