# Generated by Django 4.0.6 on 2022-07-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0002_alter_ingredients_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='calore_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='calorie number eg 500', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='obtained',
            field=models.BooleanField(blank=True, help_text='is it in the cart?', null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='serving_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='how many ounces/pounds? eg number only like 5', max_digits=10, null=True),
        ),
    ]
