# Generated by Django 4.0.6 on 2022-07-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0003_alter_ingredients_calore_per_serving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='calore_per_serving',
            field=models.DecimalField(decimal_places=2, default=0, help_text='calorie number eg 500', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='obtained',
            field=models.BooleanField(default=False, help_text='is it in the cart?'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='serving_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='how many ounces/pounds? eg number only like 5', max_digits=10),
        ),
    ]
