# Generated by Django 4.0.6 on 2022-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0004_alter_ingredients_calore_per_serving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ailse',
            field=models.DecimalField(decimal_places=0, help_text='where it is in the store approximately', max_digits=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='total price of items and ingredients', max_digits=10),
        ),
    ]
