# Generated by Django 4.0.6 on 2022-07-08 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0005_alter_ingredients_ailse_alter_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=1, help_text='how many do you want? - needs a number', max_digits=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='grocery_helper_api.ingredients'),
        ),
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_helper_api.items'),
        ),
        migrations.AlterField(
            model_name='list',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='total price of items and ingredients', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_helper_api.ingredients'),
        ),
    ]
