# Generated by Django 4.0.6 on 2022-07-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0006_alter_ingredients_amount_alter_list_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='ingredients',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='grocery_helper_api.ingredients'),
        ),
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grocery_helper_api.items'),
        ),
    ]
