# Generated by Django 4.0.6 on 2022-07-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0007_alter_list_ingredients_alter_list_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='list',
            name='ingredients',
            field=models.ManyToManyField(default=0, related_name='ingredients', to='grocery_helper_api.ingredients'),
        ),
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(default=0, to='grocery_helper_api.items'),
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(to='grocery_helper_api.ingredients'),
        ),
    ]
