# Generated by Django 4.0.6 on 2022-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0008_remove_list_ingredients_list_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ailse',
            field=models.DecimalField(decimal_places=0, help_text='where it is in the store approximately', max_digits=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='ingredients',
            field=models.ManyToManyField(default=0, related_name='list_ingredients', to='grocery_helper_api.ingredients'),
        ),
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(default=0, related_name='items', to='grocery_helper_api.items'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredients', to='grocery_helper_api.ingredients'),
        ),
    ]
