# Generated by Django 4.0.6 on 2022-07-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0009_alter_items_ailse_alter_list_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='ingredients',
            field=models.ManyToManyField(default=0, to='grocery_helper_api.ingredients'),
        ),
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(default=0, to='grocery_helper_api.items'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(to='grocery_helper_api.ingredients'),
        ),
    ]
