# Generated by Django 4.0.6 on 2022-07-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0010_alter_list_ingredients_alter_list_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='time_to_cook',
            field=models.DecimalField(decimal_places=1, default=0, help_text='how long to make it start to finish?', max_digits=3),
        ),
        migrations.AlterField(
            model_name='list',
            name='ingredients',
            field=models.ManyToManyField(to='grocery_helper_api.ingredients'),
        ),
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(to='grocery_helper_api.items'),
        ),
    ]
