# Generated by Django 4.0.6 on 2022-07-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_helper_api', '0011_recipes_time_to_cook_alter_list_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
