FROM golang:1.20.6-alpine

WORKDIR /usr/src/app
ENV GIN_MODE=release

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/grocery-helper

EXPOSE 8080

CMD ["grocery-helper"]